%% ============================================================
%% MoodBeats — Song Knowledge Base
%% songs_kb.pl
%%
%% Auto-generated by spotify_to_prolog.py (see interface/ folder).
%% This file contains seed songs for all 15 mood profiles.
%%
%% Schema:
%%   song(
%%     ID,               %% Spotify track ID (string)
%%     Title,            %% Song title (string)
%%     Artist,           %% Primary artist (string)
%%     BPM,              %% Tempo in beats per minute (integer)
%%     Energy,           %% Spotify energy score  (0.0–1.0)
%%     Instrumentalness, %% Spotify instrumentalness (0.0–1.0)
%%     Valence,          %% Spotify valence score (0.0–1.0)
%%     Tone,             %% Lyric tone atom (see mood_profiles.pl)
%%     LyricComplexity   %% simple | moderate | complex
%%   ).
%%
%% LyricComplexity derivation (used by inference_engine.pl):
%%   simple   — instrumentalness >= 0.7 (mostly instrumental)
%%   complex  — speechiness >= 0.3 (rap/spoken word)
%%   moderate — all other vocal songs
%%
%% To rebuild from Spotify:
%%   cd interface && python spotify_to_prolog.py
%% ============================================================


%% ── HAPPY ────────────────────────────────────────────────────
%% mood_profile: valence 0.7–1.0, energy 0.6–1.0, tones [positive, celebratory]

song('3n3Ppam7vgaVa1iaRUIOKE', 'Happy', 'Pharrell Williams', 160, 0.95, 0.05, 0.96, positive, moderate).
song('0nJW01T7XtvILxQgC5J7Wh', 'Levitating', 'Dua Lipa', 103, 0.83, 0.00, 0.91, positive, moderate).
song('7qiZfU4dY1lWllzX7mPBI3', 'Shape of You', 'Ed Sheeran', 96, 0.82, 0.00, 0.93, celebratory, moderate).
song('1mea3bSkSGXuIRvnydlB5b', 'Blinding Lights', 'The Weeknd', 171, 0.85, 0.00, 0.73, positive, moderate).
song('5QO79kh1waicV47BqGRL3g', 'Save Your Tears', 'The Weeknd', 118, 0.81, 0.00, 0.82, celebratory, moderate).
song('0VjIjW4GlUZAMYd2vXMi3b', 'Watermelon Sugar', 'Harry Styles', 95, 0.82, 0.00, 0.56, positive, moderate).
song('6UelLqGlWMcVH1E5c4H7lY', 'Good as Hell', 'Lizzo', 97, 0.74, 0.00, 0.79, celebratory, moderate).
song('2ekn2ttSfGqwhhate0LSR0', 'Shake It Off', 'Taylor Swift', 160, 0.80, 0.03, 0.94, positive, moderate).
song('4QNpBfC0zvjKqPJcyqBy9W', 'Can''t Stop the Feeling', 'Justin Timberlake', 113, 0.77, 0.01, 0.97, celebratory, moderate).
song('7ytR5pFWmSjzHJIeQkgog4', 'ROCKSTAR', 'DaBaby', 180, 0.61, 0.00, 0.51, positive, complex).


%% ── ENERGETIC ────────────────────────────────────────────────
%% mood_profile: valence 0.6–1.0, energy 0.8–1.0, tones [motivational, hype]

song('4iJyoBOLtHqaWYs3827at1', 'Lose Yourself', 'Eminem', 171, 0.92, 0.00, 0.68, motivational, complex).
song('0HUTL8i4y4MiGCPId7M8PT', 'Till I Collapse', 'Eminem', 171, 0.96, 0.00, 0.65, motivational, complex).
song('7dt6x5M1jzdTEt8oCbisTK', 'HUMBLE.', 'Kendrick Lamar', 150, 0.90, 0.00, 0.42, hype, complex).
song('2PSEBSgCOKPHAVxxGJpbNj', 'POWER', 'Kanye West', 134, 0.87, 0.01, 0.64, hype, complex).
song('1rfofaqEpACxVEHIZBJe6W', 'Stronger', 'Kanye West', 104, 0.85, 0.01, 0.66, motivational, complex).
song('7CZnBJGNYT5BbX7uCSrGsH', 'Run the World (Girls)', 'Beyoncé', 127, 0.92, 0.00, 0.71, hype, moderate).
song('4kbj5MwxO1bq9wjT5g9HaA', 'Eye of the Tiger', 'Survivor', 109, 0.87, 0.00, 0.93, motivational, moderate).
song('4FOd7ld9ErtSbQiXxnjRJN', 'Thunder', 'Imagine Dragons', 168, 0.87, 0.00, 0.55, hype, moderate).
song('3CRDbSIZ4r5MsZ0YwxfEkG', 'Till I Die', 'Chris Brown', 95, 0.89, 0.00, 0.87, hype, moderate).
song('7GhIk7Il098yCjg4BQjzvb', 'Mr. Brightside', 'The Killers', 148, 0.91, 0.00, 0.67, hype, moderate).


%% ── MOTIVATED ────────────────────────────────────────────────
%% mood_profile: valence 0.6–0.9, energy 0.7–1.0, tones [motivational, empowering]

song('0WqIKmW4BTrj3eJFsyRjA0', 'Unstoppable', 'Sia', 119, 0.83, 0.00, 0.70, empowering, moderate).
song('3FAJ6O0NOHQV8Mc5Ri6ENp', 'Fight Song', 'Rachel Platten', 180, 0.72, 0.01, 0.62, motivational, moderate).
song('1UGD3lW3tDmgZfAVDh6w7r', 'Roar', 'Katy Perry', 179, 0.76, 0.01, 0.76, empowering, moderate).
song('57bgtoPSgt236HzfBOd8kj', 'Firework', 'Katy Perry', 124, 0.74, 0.01, 0.82, empowering, moderate).
song('7w87IxuO7BDcJ3YvBkwZ7e', 'Confident', 'Demi Lovato', 180, 0.89, 0.00, 0.65, empowering, moderate).
song('6habFhsOp2NvshLv26DqMb', 'Run the World', 'Beyoncé', 127, 0.91, 0.00, 0.72, motivational, moderate).
song('1YQWosTIljIvxAgHWTpdBA', 'Power Trip', 'J. Cole', 82, 0.70, 0.00, 0.62, empowering, complex).
song('1P0zOhW1G9LhYbfLpQBFQG', 'Champion', 'Kanye West', 166, 0.75, 0.00, 0.69, motivational, complex).
song('3fPqWMORIxJIGBFfW0ZuAZ', 'Can I Kick It', 'A Tribe Called Quest', 105, 0.82, 0.00, 0.72, motivational, complex).
song('0e7ipj03S05BNilyu5bRzt', 'rockstar', 'Post Malone', 159, 0.71, 0.00, 0.58, empowering, moderate).


%% ── CONFIDENT ────────────────────────────────────────────────
%% mood_profile: valence 0.65–0.95, energy 0.65–0.95, tones [assertive, empowering]

song('7MXVkk9YMctZqd1Srtv4MB', 'God''s Plan', 'Drake', 77, 0.73, 0.00, 0.71, assertive, complex).
song('3ee8Jmje8o58CHK66QrVC2', 'SICKO MODE', 'Travis Scott', 155, 0.84, 0.00, 0.68, assertive, complex).
song('5Z01UMMf7V1o0MzF86s6WJ', 'Money Longer', 'Lil Uzi Vert', 133, 0.82, 0.00, 0.70, assertive, complex).
song('6l8EbYSEqHsgMzSHMPEMgj', '99 Problems', 'Jay-Z', 103, 0.85, 0.00, 0.36, assertive, complex).
song('5gjVgP8jPEWIoHAbaqDrVi', 'Run This Town', 'Jay-Z', 96, 0.86, 0.00, 0.23, empowering, complex).
song('4u7EnebtmKWzUH433cf5Qv', 'Empire State of Mind', 'Jay-Z', 82, 0.67, 0.01, 0.51, empowering, moderate).
song('5YqItcommon48iLZOgK', 'Common People', 'Pulp', 144, 0.70, 0.00, 0.73, assertive, moderate).
song('2takcwOaAZWiXQijPHIx7B', 'Gold Digger', 'Kanye West', 112, 0.78, 0.01, 0.82, assertive, complex).
song('1dGr1c8CrMLDpV6mPbImSI', 'All of the Lights', 'Kanye West', 92, 0.78, 0.00, 0.49, empowering, complex).
song('1TfqLAPs4K3s2rJMoCokcS', 'Bitch Better Have My Money', 'Rihanna', 130, 0.87, 0.00, 0.75, assertive, moderate).


%% ── ANGRY ────────────────────────────────────────────────────
%% mood_profile: valence 0.0–0.35, energy 0.8–1.0, tones [aggressive, cathartic]

song('6GNXHPYBfBvrvfCa1IHqEi', 'Break Stuff', 'Limp Bizkit', 113, 0.96, 0.00, 0.27, aggressive, moderate).
song('3bxFeqr3WLdHXhIlNzFNgB', 'Killing in the Name', 'Rage Against the Machine', 115, 0.97, 0.02, 0.17, aggressive, moderate).
song('6PQ88X9TkUIAUIZJHW2upE', 'Bulls on Parade', 'Rage Against the Machine', 130, 0.97, 0.00, 0.20, cathartic, moderate).
song('5rCHhtTcnFgSmrOBHMiI1z', 'Numb', 'Linkin Park', 100, 0.91, 0.00, 0.19, cathartic, moderate).
song('3TO7jtDp3kvkRRMWzwnOxm', 'In the End', 'Linkin Park', 105, 0.90, 0.01, 0.26, cathartic, moderate).
song('7lFO4TqAfhAMTZGDFoGZWA', 'Last Resort', 'Papa Roach', 161, 0.95, 0.00, 0.18, aggressive, moderate).
song('2gXTOMKTNqpgjChc6GkChH', 'Du Hast', 'Rammstein', 130, 0.98, 0.01, 0.09, aggressive, moderate).
song('4Fkqra83J8Qcs7HETfcLit', 'Chop Suey!', 'System of a Down', 141, 0.97, 0.00, 0.30, cathartic, moderate).
song('3pnynDkn6kF8bMuXWDPoFS', 'B.Y.O.B.', 'System of a Down', 162, 0.98, 0.00, 0.12, aggressive, complex).
song('5Cjbz0fGjEoIbXkXbhC7Qi', 'Before I Forget', 'Slipknot', 145, 0.97, 0.00, 0.22, aggressive, moderate).


%% ── ANXIOUS ──────────────────────────────────────────────────
%% mood_profile: valence 0.1–0.4, energy 0.5–0.8, tones [soothing, neutral]

song('4aebBr4JAihzJQR0CiIZJv', 'Weightless', 'Marconi Union', 60, 0.26, 0.97, 0.16, soothing, simple).
song('3I5fpHe8iBMkEkCb6FrLbV', 'Clair de Lune', 'Claude Debussy', 68, 0.18, 0.98, 0.22, soothing, simple).
song('5YSbkX7fMEqICiWKunJVFD', 'Experience', 'Ludovico Einaudi', 76, 0.29, 0.97, 0.24, neutral, simple).
song('0pAFb3bqKFiJGeOqwqSl7p', 'Gymnopédie No.1', 'Erik Satie', 64, 0.17, 0.98, 0.21, soothing, simple).
song('4mPQoWiuKalSnhqMdRdq4x', 'Breathe (2 AM)', 'Anna Nalick', 72, 0.51, 0.01, 0.18, neutral, moderate).
song('1uEYHLBwQ9uyIhWGGXqkm8', 'The Night Will Always Win', 'Manchester Orchestra', 80, 0.55, 0.00, 0.25, soothing, moderate).
song('4Dg5monameSiASKpFRt5Nk', 'Skinny Love', 'Bon Iver', 74, 0.57, 0.00, 0.29, neutral, moderate).
song('51EC3PQ4SBbQEPjXPzWGtx', 'Holocene', 'Bon Iver', 100, 0.60, 0.02, 0.30, neutral, moderate).
song('2bNjqsnmOBqRJvjiEzjkNK', 'Motion Picture Soundtrack', 'Kanye West', 66, 0.52, 0.00, 0.26, soothing, moderate).
song('7EjyzZcbLxW7PaaLua9KnT', 'Teardrop', 'Massive Attack', 95, 0.62, 0.14, 0.22, neutral, moderate).


%% ── STRESSED ─────────────────────────────────────────────────
%% mood_profile: valence 0.1–0.4, energy 0.55–0.85, tones [soothing, neutral]

song('2374M6RcuuTJKiVK4CqkRM', 'Breathe', 'Pink Floyd', 63, 0.63, 0.01, 0.38, soothing, moderate).
song('7F4FxJVKDhNqLRnFQz4rqH', 'Brain Damage', 'Pink Floyd', 87, 0.58, 0.01, 0.35, neutral, moderate).
song('6dGnYIeXmHdcikdzNNDMm2', 'The Sound of Silence', 'Simon & Garfunkel', 98, 0.61, 0.00, 0.24, soothing, moderate).
song('2tXgnF9lZK0IJz01YbSiRN', 'High and Dry', 'Radiohead', 97, 0.59, 0.01, 0.18, neutral, moderate).
song('3WkgnTiMEJC1TiWr0APUYT', 'Exit Music (For a Film)', 'Radiohead', 76, 0.57, 0.01, 0.11, soothing, moderate).
song('12YpEfN3hQXJH0L3KcMG5I', 'Pyramid Song', 'Radiohead', 66, 0.55, 0.01, 0.22, soothing, moderate).
song('2WNncEWAV8yFtxVakB4RKl', 'Riptide', 'Vance Joy', 100, 0.73, 0.00, 0.39, neutral, moderate).
song('5nqdFkUJEuNRBMBDK7M64e', 'Mad World', 'Gary Jules', 96, 0.57, 0.00, 0.14, neutral, moderate).
song('3kxfsdsCpFgN412fpnW85Y', 'River', 'Joni Mitchell', 75, 0.60, 0.00, 0.29, neutral, moderate).
song('7BrF5Dl0DkAzPSv9iUXwVh', 'Strange Fruit', 'Nina Simone', 61, 0.56, 0.00, 0.18, soothing, moderate).


%% ── SAD ──────────────────────────────────────────────────────
%% mood_profile: valence 0.0–0.35, energy 0.1–0.45, tones [melancholic, reflective]

song('3n3Ppam7vgaVa1iaRUIOKf', 'Someone Like You', 'Adele', 68, 0.28, 0.00, 0.18, melancholic, moderate).
song('6tNQ70jh4OwmPGpYy6R2o9', 'The Night We Met', 'Lord Huron', 79, 0.30, 0.01, 0.30, reflective, moderate).
song('3a1lNhkSLSkpJkSKGsePbp', 'Skinny', 'Billie Eilish', 70, 0.25, 0.00, 0.09, melancholic, moderate).
song('6SpLc7EXZIPpy0sVko0aoU', 'All I Want', 'Kodaline', 77, 0.31, 0.00, 0.19, melancholic, moderate).
song('3WIUbLnVkpuKRMiA6aChFO', 'Liability', 'Lorde', 83, 0.35, 0.00, 0.17, reflective, moderate).
song('3JOIVTQ1Ww7QihtSBpMHfO', 'When the Party Is Over', 'Billie Eilish', 73, 0.19, 0.01, 0.22, melancholic, moderate).
song('7kRSZkdnT8gFLZr9Yke0Gk', 'Motion Picture Soundtrack', 'Radiohead', 66, 0.15, 0.00, 0.06, reflective, moderate).
song('4ozFBE8Bv7d5Gn4FrFqBuQ', 'Wish You Were Here', 'Pink Floyd', 66, 0.32, 0.02, 0.32, reflective, moderate).
song('5KawlOMHjWeUjQtnuRs22c', 'Fix You', 'Coldplay', 69, 0.22, 0.00, 0.22, melancholic, moderate).
song('2takcwOaAZWiXQijPHIx7A', 'Street Spirit', 'Radiohead', 67, 0.18, 0.00, 0.07, reflective, moderate).


%% ── MELANCHOLIC ──────────────────────────────────────────────
%% mood_profile: valence 0.1–0.4, energy 0.1–0.4, tones [reflective, bittersweet]

song('2Fxmhks0bxGSBdJ92vM42m', 'drivers license', 'Olivia Rodrigo', 81, 0.25, 0.00, 0.12, reflective, moderate).
song('7MXVkk9YMctZqd1Srtv4MA', 'The Night We Met', 'Lord Huron', 79, 0.30, 0.01, 0.30, reflective, moderate).
song('6WUjFvz4KBzYJdWFqQqPBU', 'Casimir Pulaski Day', 'Sufjan Stevens', 55, 0.31, 0.01, 0.25, bittersweet, moderate).
song('4ozFBE8Bv7d5Gn4FrFqBuA', 'Video Games', 'Lana Del Rey', 82, 0.32, 0.00, 0.16, bittersweet, moderate).
song('01FIhNcCRqdzPgjZOlHCeM', 'Blue (Da Ba Dee)', 'Eiffel 65', 86, 0.40, 0.00, 0.38, bittersweet, moderate).
song('2BwTFqVL9UZUFClajOL0GR', 'Skinny Love', 'Birdy', 78, 0.33, 0.00, 0.29, reflective, moderate).
song('6N1Q8BdT0Ft11PvZwDaizJ', 'Liability (Reprise)', 'Lorde', 90, 0.35, 0.00, 0.22, reflective, moderate).
song('7IxuHJKIc3RknGgRMBdUeS', 'Exile', 'Taylor Swift', 73, 0.37, 0.00, 0.14, bittersweet, moderate).
song('5GorFaKkUWhSJzh9IWAEbM', 'Fade Into You', 'Mazzy Star', 76, 0.24, 0.00, 0.28, reflective, moderate).
song('0YQsAMaXRFBu3vx31JJ1k5', 'Slow Show', 'The National', 72, 0.35, 0.00, 0.34, bittersweet, moderate).


%% ── TIRED ────────────────────────────────────────────────────
%% mood_profile: valence 0.2–0.5, energy 0.1–0.35, tones [neutral, calm]

song('4aebBr4JAihzJQR0CiIZJw', 'Weightless Pt. 2', 'Marconi Union', 55, 0.20, 0.97, 0.42, calm, simple).
song('6rZiLeOF8W6RUQEpGWj5LY', 'Sleep', 'Max Richter', 60, 0.15, 0.98, 0.30, calm, simple).
song('7GwfQgqxSoEeFHxBwilzVH', 'On the Nature of Daylight', 'Max Richter', 50, 0.13, 0.98, 0.31, calm, simple).
song('3B0WvKSl0qVwMWFJhlOBle', 'November', 'Max Richter', 67, 0.17, 0.97, 0.25, neutral, simple).
song('4SFBV7SRNG1bKHOY3JpW7i', 'Porcelain', 'Moby', 72, 0.19, 0.87, 0.44, calm, simple).
song('5WDzpFqVxNnkfXJFdqpmpH', 'Intro', 'The xx', 75, 0.26, 0.71, 0.47, calm, simple).
song('1x8ZrpBg11x4jGCkCw4pWd', 'Crystalline', 'Björk', 65, 0.28, 0.01, 0.35, neutral, moderate).
song('5qDWBSvX7YqCJFHLxEcHxF', 'To Be Alone', 'Hozier', 67, 0.33, 0.01, 0.42, neutral, moderate).
song('5JXFdWvK9TnFuiTsEP5KMM', 'Naked as We Came', 'Iron & Wine', 55, 0.30, 0.00, 0.49, calm, moderate).
song('7mXMYRzRRvCHVMFbqX7F8U', 'Such Great Heights', 'The Postal Service', 79, 0.32, 0.41, 0.44, neutral, moderate).


%% ── BORED ────────────────────────────────────────────────────
%% mood_profile: valence 0.3–0.55, energy 0.2–0.5, tones [positive, neutral]

song('3h0zDPPKkBJVoCSSe0h3bY', 'Electric Feel', 'MGMT', 104, 0.48, 0.01, 0.48, positive, moderate).
song('5CtI0EqFnDMpMMAlVmhD6O', 'Young Folks', 'Peter Bjorn and John', 112, 0.41, 0.03, 0.54, positive, moderate).
song('7ERqXTdTVBaJJ6KTxHsOId', 'Take It Easy', 'Eagles', 93, 0.33, 0.01, 0.51, neutral, moderate).
song('3sT1bQQJe8Yeh3I3Kyvmzl', 'Float On', 'Modest Mouse', 103, 0.47, 0.00, 0.53, positive, moderate).
song('4eiGhMbgBvQNu0kWn0mP5p', 'Mr. Blue Sky', 'Electric Light Orchestra', 128, 0.47, 0.01, 0.55, positive, moderate).
song('5CQ30WqJwcep0pYcV4AMNc', 'Africa', 'Toto', 93, 0.45, 0.00, 0.44, neutral, moderate).
song('6RRefCOCDVMiMEGBnJoEQ5', 'Here Comes the Sun', 'The Beatles', 129, 0.42, 0.00, 0.51, positive, moderate).
song('3yfqSUWxFvZELEM4PmlwIR', 'Dreams', 'Fleetwood Mac', 120, 0.38, 0.00, 0.45, neutral, moderate).
song('7tFiyTwD0nx5a1eklYtX2J', 'Lovely Day', 'Bill Withers', 92, 0.46, 0.00, 0.53, positive, moderate).
song('4U45aEWtQhrm8A5mxPaLDl', 'Uptight (Everything Is Alright)', 'Stevie Wonder', 121, 0.50, 0.00, 0.55, positive, moderate).


%% ── CALM ─────────────────────────────────────────────────────
%% mood_profile: valence 0.5–0.8, energy 0.1–0.45, tones [soothing, neutral]

song('5nqdFkUJEuNRBMBDK7M64d', 'Clair de Lune (Reprise)', 'Joep Beving', 62, 0.18, 0.97, 0.64, soothing, simple).
song('4sB0STbPO1HjH5iyBGKGy2', 'River Flows in You', 'Yiruma', 68, 0.22, 0.98, 0.68, soothing, simple).
song('4L1HDyfdGIRb5NxNsKFwbE', 'Comptine d\'un autre été', 'Yann Tiersen', 75, 0.24, 0.97, 0.62, soothing, simple).
song('0pqnGHJpmpxLKifKRmU6WP', 'An Ending (Ascent)', 'Brian Eno', 55, 0.19, 0.97, 0.55, soothing, simple).
song('0GjEhVFGZW8afUYGChu3Rr', 'Sunburn', 'Muse', 72, 0.31, 0.00, 0.64, neutral, moderate).
song('3KkXRkHbMCARz0aVfEt68P', 'Yellow', 'Coldplay', 87, 0.42, 0.01, 0.69, neutral, moderate).
song('02M6vucOvmRfMxTXDCBPcC', 'Vienna', 'Billy Joel', 67, 0.33, 0.00, 0.72, soothing, moderate).
song('5ihS6UUlyQAfmp48eSkwuQ', 'The Night Will Always Win', 'Manchester Orchestra', 90, 0.44, 0.00, 0.55, soothing, moderate).
song('4CvTDPKA6W06DRfBnZKnbX', 'Atlas Hands', 'Benjamin Francis Leftwich', 75, 0.35, 0.00, 0.56, neutral, moderate).
song('6RIFRRpy1qyc8QeQsSanpv', 'Wander', 'Tycho', 83, 0.41, 0.83, 0.73, soothing, simple).


%% ── ROMANTIC ─────────────────────────────────────────────────
%% mood_profile: valence 0.55–0.85, energy 0.2–0.55, tones [romantic, intimate]

song('3n3Ppam7vgaVa1iaRUIOKg', 'Perfect', 'Ed Sheeran', 95, 0.45, 0.00, 0.68, romantic, moderate).
song('3KkXRkHbMCARz0aVfEt68Q', 'Make You Feel My Love', 'Adele', 70, 0.24, 0.00, 0.66, intimate, moderate).
song('0GjEhVFGZW8afUYGChu3Rs', 'La Vie en Rose', 'Édith Piaf', 68, 0.29, 0.00, 0.72, romantic, moderate).
song('5ihS6UUlyQAfmp48eSkwuR', 'Thinking Out Loud', 'Ed Sheeran', 79, 0.52, 0.00, 0.71, romantic, moderate).
song('02M6vucOvmRfMxTXDCBPcD', 'Just the Two of Us', 'Bill Withers', 75, 0.34, 0.00, 0.64, intimate, moderate).
song('3KkXRkHbMCARz0aVfEt68R', 'Come Away with Me', 'Norah Jones', 84, 0.33, 0.00, 0.59, romantic, moderate).
song('6RIFRRpy1qyc8QeQsSanpu', 'Can''t Help Falling in Love', 'Elvis Presley', 65, 0.27, 0.01, 0.76, romantic, moderate).
song('4CvTDPKA6W06DRfBnZKnbW', 'The Book of Love', 'Peter Gabriel', 63, 0.26, 0.00, 0.58, intimate, moderate).
song('4sB0STbPO1HjH5iyBGKGy3', 'Bloom', 'The Paper Kites', 92, 0.49, 0.00, 0.73, romantic, moderate).
song('4L1HDyfdGIRb5NxNsKFwbF', 'Lover', 'Taylor Swift', 68, 0.45, 0.00, 0.84, romantic, moderate).


%% ── NOSTALGIC ────────────────────────────────────────────────
%% mood_profile: valence 0.4–0.75, energy 0.2–0.55, tones [reflective, bittersweet]

song('5QO79kh1waicV47BqGRL3h', 'Fast Car', 'Tracy Chapman', 99, 0.49, 0.00, 0.42, reflective, moderate).
song('0nJW01T7XtvILxQgC5J7Wg', 'Landslide', 'Fleetwood Mac', 76, 0.30, 0.02, 0.41, reflective, moderate).
song('7qiZfU4dY1lWllzX7mPBI4', 'Time After Time', 'Cyndi Lauper', 89, 0.48, 0.00, 0.56, bittersweet, moderate).
song('1mea3bSkSGXuIRvnydlB5c', 'The Sound of Silence', 'Simon & Garfunkel', 98, 0.37, 0.00, 0.40, reflective, moderate).
song('3tVQdUvClmAT7URs9V3rsp', 'Yesterday', 'The Beatles', 96, 0.44, 0.00, 0.42, bittersweet, moderate).
song('0VjIjW4GlUZAMYd2vXMi3c', 'Summer of 69', 'Bryan Adams', 140, 0.54, 0.00, 0.63, bittersweet, moderate).
song('6UelLqGlWMcVH1E5c4H7lZ', 'Take On Me', 'a-ha', 169, 0.52, 0.00, 0.70, bittersweet, moderate).
song('2ekn2ttSfGqwhhate0LSR1', 'Bohemian Rhapsody', 'Queen', 144, 0.40, 0.00, 0.44, reflective, moderate).
song('4QNpBfC0zvjKqPJcyqBy9X', 'Hotel California', 'Eagles', 75, 0.43, 0.03, 0.38, reflective, moderate).
song('7ytR5pFWmSjzHJIeQkgog5', 'Sweet Home Alabama', 'Lynyrd Skynyrd', 98, 0.48, 0.01, 0.62, bittersweet, moderate).


%% ── FOCUSED ──────────────────────────────────────────────────
%% mood_profile: valence 0.4–0.7, energy 0.3–0.65, tones [neutral, instrumental]

song('7kRSZkdnT8gFLZr9Yke0Gh', 'Experience', 'Ludovico Einaudi', 76, 0.34, 0.97, 0.41, instrumental, simple).
song('3a1lNhkSLSkpJkSKGsePbc', 'Divenire', 'Ludovico Einaudi', 80, 0.44, 0.97, 0.55, instrumental, simple).
song('6SpLc7EXZIPpy0sVko0aoV', 'Nuvole Bianche', 'Ludovico Einaudi', 60, 0.38, 0.98, 0.44, instrumental, simple).
song('3WIUbLnVkpuKRMiA6aChFP', 'Opus 23', 'Dustin O\'Halloran', 75, 0.40, 0.97, 0.49, instrumental, simple).
song('3JOIVTQ1Ww7QihtSBpMHfP', 'Comptine d\'un autre été (Solo)', 'Yann Tiersen', 75, 0.30, 0.97, 0.42, instrumental, simple).
song('7IxuHJKIc3RknGgRMBdUeT', 'Time', 'Hans Zimmer', 63, 0.37, 0.97, 0.59, instrumental, simple).
song('5GorFaKkUWhSJzh9IWAEbN', 'Strobe', 'deadmau5', 128, 0.47, 0.85, 0.42, neutral, simple).
song('0YQsAMaXRFBu3vx31JJ1k6', 'Chocolate', 'The 1975', 95, 0.56, 0.00, 0.55, neutral, moderate).
song('3h0zDPPKkBJVoCSSe0h3bZ', 'Retrograde', 'James Blake', 83, 0.46, 0.02, 0.43, neutral, moderate).
song('5CtI0EqFnDMpMMAlVmhD6P', 'Teardrop', 'Massive Attack', 96, 0.54, 0.14, 0.41, neutral, moderate).